export const GET_CARTEIRAS = 'GET_CARTEIRAS';

export const GET_CARTEIRA = 'GET_CARTEIRA';

export const ADD_CARTEIRA = 'ADD_CARTEIRA';

export const UPDATE_CARTEIRA = 'UPDATE_CARTEIRA';

export const GET_GECEX = 'GET_GECEX';

/** USER */
export const GET_USER = 'GET_USER';

/** CLIENTES */
export const GET_CLIENTES = 'GET_CLIENTES';

/** NOTIFY_USER */
export const NOTIFY_USER = 'NOTIFY_USER';

/** SETTINGS */
export const PERMITE_VER_TODAS_GECEX = 'PERMITE_VER_TODAS_GECEX';

/** CLIENTES SELECIONADOS PARA MUDANÇA */

export const ADD_SELECTED_CLIENTS = 'ADD_SELECTED_CLIENTS';

export const GET_SELECTED_CLIENTS = 'GET_SELECTED_CLIENTS';

export const DELETE_SELECTED_CLIENTS = 'DELETE_SELECTED_CLIENTS';
